### ISSUE TITLE
월요일 스터디

### ISSUE THREAD

**Issue by gyunggyung** [ElenaSSun/ML-study#1]
- [ ] 공부 방향 잡기, 숙제를 정확한 범위를 줄지 아니면 자유도를 줄지
- [ ] 흥미 불러 일으키기
- [ ] 공부의 우선순위 정하기
- [ ] 깃허브와 오픈소스에 대한 설명
- [ ] 파이썬 익숙해지기
- [ ] md파일 등등 기존에 있는 거를 응용하는 법 공부

**Comment by newhiwoong** [comment]
+ 깃허브와 오픈소스에 대한 설명
+ 파이썬 익숙해지기
+ md파일 등등 기존에 있는 거를 응용하는 법 공부

**Comment by gyunggyung** [comment]
**수요일로 이동**
