### ISSUE TITLE
2019년 04월 24일 스터디

### ISSUE THREAD

**Issue by gyunggyung** [ElenaSSun/ML-study#3]
- [ ] 질문 받기
- [ ] 공부 방향 잡기, 숙제를 정확한 범위를 줄지 아니면 자유도를 줄지
- [ ] 흥미 불러 일으키기
- [ ] 공부의 우선순위 정하기
- [ ] 깃허브와 오픈소스에 대한 설명

## 다음에 할 일 or 숙제
 
파이썬 익숙해지기
md파일 등등 기존에 있는 거를 응용하는 법 공부
깃허브 스타 달아보기
코드 해석 해보기

**Comment by ElenaSSun** [comment]
test
