### ISSUE TITLE
2019년 4월 30일 스터디

### ISSUE THREAD

**Issue by gyunggyung** [ElenaSSun/ML-study#4]
- [x] 질문 받기
- [x] 공부 방향 잡기, 숙제를 정확한 범위를 줄지 아니면 자유도를 줄지
- [x] 흥미 불러 일으키기
- [x] 공부의 우선순위 정하기
- [x] 깃허브와 오픈소스에 대한 설명
- [x] 깃허브 스타 달아보기
- [x] Issues, Pull 등등 github 각종 기능 설명
- [ ] md파일 등등 기존에 있는 거를 응용하는 법 공부

## 다음에 할 일 or 숙제
 
파이썬 익숙해지기
코드 해석 해보기

**Comment by ElenaSSun** [comment]
https://github.com/Insight-book/data-science-from-scratch/blob/master/notebook/ch06_probability.ipynb

에서 복붙하기


베이즈 정리

https://j1w2k3.tistory.com/1009

http://blog.naver.com/PostView.nhn?blogId=mykepzzang&logNo=220834940797


구글에 모르는 단어들을 많이 검색해보자.

7장까지 하고 딥러닝 책 공부

**Comment by ElenaSSun** [comment]
선형대수 배운데까지 다시 공부.
이 다음 딥러닝 할 수 있는데까지.

**Comment by gyunggyung** [comment]
끝 아쿠아리움 가자~
